//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RamonSchool.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NoteShareWSSoap", Namespace="http://tempuri.org/")]
    public partial class NoteShareWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllNotebooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNotebookByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserFromNotebookOperationCompleted;
        
        private System.Threading.SendOrPostCallback LikeNotebookOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnLikeNotebookOperationCompleted;
        
        private System.Threading.SendOrPostCallback CommentOnNotebookOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCommentsOfNotebookOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubjectByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLikeCountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NoteShareWS() {
            this.Url = global::RamonSchool.Properties.Settings.Default.RamonSchool_localhost_NoteShareWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllNotebooksCompletedEventHandler GetAllNotebooksCompleted;
        
        /// <remarks/>
        public event GetNotebookByIdCompletedEventHandler GetNotebookByIdCompleted;
        
        /// <remarks/>
        public event GetUserFromNotebookCompletedEventHandler GetUserFromNotebookCompleted;
        
        /// <remarks/>
        public event LikeNotebookCompletedEventHandler LikeNotebookCompleted;
        
        /// <remarks/>
        public event UnLikeNotebookCompletedEventHandler UnLikeNotebookCompleted;
        
        /// <remarks/>
        public event CommentOnNotebookCompletedEventHandler CommentOnNotebookCompleted;
        
        /// <remarks/>
        public event GetCommentsOfNotebookCompletedEventHandler GetCommentsOfNotebookCompleted;
        
        /// <remarks/>
        public event GetSubjectByIdCompletedEventHandler GetSubjectByIdCompleted;
        
        /// <remarks/>
        public event GetLikeCountCompletedEventHandler GetLikeCountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllNotebooks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NotebookWS[] GetAllNotebooks() {
            object[] results = this.Invoke("GetAllNotebooks", new object[0]);
            return ((NotebookWS[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllNotebooksAsync() {
            this.GetAllNotebooksAsync(null);
        }
        
        /// <remarks/>
        public void GetAllNotebooksAsync(object userState) {
            if ((this.GetAllNotebooksOperationCompleted == null)) {
                this.GetAllNotebooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllNotebooksOperationCompleted);
            }
            this.InvokeAsync("GetAllNotebooks", new object[0], this.GetAllNotebooksOperationCompleted, userState);
        }
        
        private void OnGetAllNotebooksOperationCompleted(object arg) {
            if ((this.GetAllNotebooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllNotebooksCompleted(this, new GetAllNotebooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNotebookById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NotebookWS GetNotebookById(int id) {
            object[] results = this.Invoke("GetNotebookById", new object[] {
                        id});
            return ((NotebookWS)(results[0]));
        }
        
        /// <remarks/>
        public void GetNotebookByIdAsync(int id) {
            this.GetNotebookByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetNotebookByIdAsync(int id, object userState) {
            if ((this.GetNotebookByIdOperationCompleted == null)) {
                this.GetNotebookByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNotebookByIdOperationCompleted);
            }
            this.InvokeAsync("GetNotebookById", new object[] {
                        id}, this.GetNotebookByIdOperationCompleted, userState);
        }
        
        private void OnGetNotebookByIdOperationCompleted(object arg) {
            if ((this.GetNotebookByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNotebookByIdCompleted(this, new GetNotebookByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserFromNotebook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserWS GetUserFromNotebook(NotebookWS notebook) {
            object[] results = this.Invoke("GetUserFromNotebook", new object[] {
                        notebook});
            return ((UserWS)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserFromNotebookAsync(NotebookWS notebook) {
            this.GetUserFromNotebookAsync(notebook, null);
        }
        
        /// <remarks/>
        public void GetUserFromNotebookAsync(NotebookWS notebook, object userState) {
            if ((this.GetUserFromNotebookOperationCompleted == null)) {
                this.GetUserFromNotebookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserFromNotebookOperationCompleted);
            }
            this.InvokeAsync("GetUserFromNotebook", new object[] {
                        notebook}, this.GetUserFromNotebookOperationCompleted, userState);
        }
        
        private void OnGetUserFromNotebookOperationCompleted(object arg) {
            if ((this.GetUserFromNotebookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserFromNotebookCompleted(this, new GetUserFromNotebookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LikeNotebook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LikeNotebook(NotebookWS notebook) {
            this.Invoke("LikeNotebook", new object[] {
                        notebook});
        }
        
        /// <remarks/>
        public void LikeNotebookAsync(NotebookWS notebook) {
            this.LikeNotebookAsync(notebook, null);
        }
        
        /// <remarks/>
        public void LikeNotebookAsync(NotebookWS notebook, object userState) {
            if ((this.LikeNotebookOperationCompleted == null)) {
                this.LikeNotebookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLikeNotebookOperationCompleted);
            }
            this.InvokeAsync("LikeNotebook", new object[] {
                        notebook}, this.LikeNotebookOperationCompleted, userState);
        }
        
        private void OnLikeNotebookOperationCompleted(object arg) {
            if ((this.LikeNotebookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LikeNotebookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UnLikeNotebook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UnLikeNotebook(NotebookWS notebook) {
            this.Invoke("UnLikeNotebook", new object[] {
                        notebook});
        }
        
        /// <remarks/>
        public void UnLikeNotebookAsync(NotebookWS notebook) {
            this.UnLikeNotebookAsync(notebook, null);
        }
        
        /// <remarks/>
        public void UnLikeNotebookAsync(NotebookWS notebook, object userState) {
            if ((this.UnLikeNotebookOperationCompleted == null)) {
                this.UnLikeNotebookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnLikeNotebookOperationCompleted);
            }
            this.InvokeAsync("UnLikeNotebook", new object[] {
                        notebook}, this.UnLikeNotebookOperationCompleted, userState);
        }
        
        private void OnUnLikeNotebookOperationCompleted(object arg) {
            if ((this.UnLikeNotebookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnLikeNotebookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CommentOnNotebook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CommentOnNotebook(string comment, NotebookWS notebook) {
            this.Invoke("CommentOnNotebook", new object[] {
                        comment,
                        notebook});
        }
        
        /// <remarks/>
        public void CommentOnNotebookAsync(string comment, NotebookWS notebook) {
            this.CommentOnNotebookAsync(comment, notebook, null);
        }
        
        /// <remarks/>
        public void CommentOnNotebookAsync(string comment, NotebookWS notebook, object userState) {
            if ((this.CommentOnNotebookOperationCompleted == null)) {
                this.CommentOnNotebookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommentOnNotebookOperationCompleted);
            }
            this.InvokeAsync("CommentOnNotebook", new object[] {
                        comment,
                        notebook}, this.CommentOnNotebookOperationCompleted, userState);
        }
        
        private void OnCommentOnNotebookOperationCompleted(object arg) {
            if ((this.CommentOnNotebookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CommentOnNotebookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCommentsOfNotebook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CommentWS[] GetCommentsOfNotebook(NotebookWS notebook) {
            object[] results = this.Invoke("GetCommentsOfNotebook", new object[] {
                        notebook});
            return ((CommentWS[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCommentsOfNotebookAsync(NotebookWS notebook) {
            this.GetCommentsOfNotebookAsync(notebook, null);
        }
        
        /// <remarks/>
        public void GetCommentsOfNotebookAsync(NotebookWS notebook, object userState) {
            if ((this.GetCommentsOfNotebookOperationCompleted == null)) {
                this.GetCommentsOfNotebookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCommentsOfNotebookOperationCompleted);
            }
            this.InvokeAsync("GetCommentsOfNotebook", new object[] {
                        notebook}, this.GetCommentsOfNotebookOperationCompleted, userState);
        }
        
        private void OnGetCommentsOfNotebookOperationCompleted(object arg) {
            if ((this.GetCommentsOfNotebookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCommentsOfNotebookCompleted(this, new GetCommentsOfNotebookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubjectById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSubjectById(int subjectId) {
            object[] results = this.Invoke("GetSubjectById", new object[] {
                        subjectId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSubjectByIdAsync(int subjectId) {
            this.GetSubjectByIdAsync(subjectId, null);
        }
        
        /// <remarks/>
        public void GetSubjectByIdAsync(int subjectId, object userState) {
            if ((this.GetSubjectByIdOperationCompleted == null)) {
                this.GetSubjectByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubjectByIdOperationCompleted);
            }
            this.InvokeAsync("GetSubjectById", new object[] {
                        subjectId}, this.GetSubjectByIdOperationCompleted, userState);
        }
        
        private void OnGetSubjectByIdOperationCompleted(object arg) {
            if ((this.GetSubjectByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubjectByIdCompleted(this, new GetSubjectByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLikeCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetLikeCount(NotebookWS notebook) {
            object[] results = this.Invoke("GetLikeCount", new object[] {
                        notebook});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetLikeCountAsync(NotebookWS notebook) {
            this.GetLikeCountAsync(notebook, null);
        }
        
        /// <remarks/>
        public void GetLikeCountAsync(NotebookWS notebook, object userState) {
            if ((this.GetLikeCountOperationCompleted == null)) {
                this.GetLikeCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLikeCountOperationCompleted);
            }
            this.InvokeAsync("GetLikeCount", new object[] {
                        notebook}, this.GetLikeCountOperationCompleted, userState);
        }
        
        private void OnGetLikeCountOperationCompleted(object arg) {
            if ((this.GetLikeCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLikeCountCompleted(this, new GetLikeCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NotebookWS {
        
        private int notebookIdField;
        
        private int userIdField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string colorField;
        
        private string formatField;
        
        private string pathField;
        
        private System.DateTime createdDateField;
        
        private System.DateTime updateDateField;
        
        private string accessibilityField;
        
        private System.Nullable<int> schoolIdField;
        
        private int subjectIdField;
        
        private string onlineNotebookFormatField;
        
        /// <remarks/>
        public int NotebookId {
            get {
                return this.notebookIdField;
            }
            set {
                this.notebookIdField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        public string Accessibility {
            get {
                return this.accessibilityField;
            }
            set {
                this.accessibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SchoolId {
            get {
                return this.schoolIdField;
            }
            set {
                this.schoolIdField = value;
            }
        }
        
        /// <remarks/>
        public int SubjectId {
            get {
                return this.subjectIdField;
            }
            set {
                this.subjectIdField = value;
            }
        }
        
        /// <remarks/>
        public string OnlineNotebookFormat {
            get {
                return this.onlineNotebookFormatField;
            }
            set {
                this.onlineNotebookFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CommentWS {
        
        private int userIdField;
        
        private int notebookIdField;
        
        private string commentField;
        
        private string usernameField;
        
        private System.DateTime createdDateField;
        
        private int commentIdField;
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public int NotebookId {
            get {
                return this.notebookIdField;
            }
            set {
                this.notebookIdField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public int CommentId {
            get {
                return this.commentIdField;
            }
            set {
                this.commentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserWS {
        
        private int userIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string passwordField;
        
        private string permissionField;
        
        private System.DateTime birthdayField;
        
        private string addressField;
        
        private string usernameField;
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetAllNotebooksCompletedEventHandler(object sender, GetAllNotebooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllNotebooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllNotebooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NotebookWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NotebookWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetNotebookByIdCompletedEventHandler(object sender, GetNotebookByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNotebookByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNotebookByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NotebookWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NotebookWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetUserFromNotebookCompletedEventHandler(object sender, GetUserFromNotebookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserFromNotebookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserFromNotebookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LikeNotebookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UnLikeNotebookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CommentOnNotebookCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCommentsOfNotebookCompletedEventHandler(object sender, GetCommentsOfNotebookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCommentsOfNotebookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCommentsOfNotebookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CommentWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CommentWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetSubjectByIdCompletedEventHandler(object sender, GetSubjectByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubjectByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubjectByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetLikeCountCompletedEventHandler(object sender, GetLikeCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLikeCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLikeCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591